import threading
import os
try:
    from pptx import Presentation
except ImportError:
    pass
try:
    import ollama
except ImportError:
    pass

def handle_query(query, app):
    # The Trigger
    if not query.startswith("create a ppt on "):
        return False

    topic = query.replace("create a ppt on ", "", 1).strip()
    app.safe_append_chat("SYSTEM", f"[PPT Engine] Assembling presentation on: '{topic}'...")
    app.speak_async(f"Compiling slide deck for {topic}.")

    def ppt_worker():
        try:
            # 1. Ask Llama 3 for the slide content in a very strict format
            app.safe_append_chat("SYSTEM", "[PPT Engine] Brainstorming slide content with Core...")
            prompt = f"""Write a 5-slide presentation about {topic}. 
            Format your response EXACTLY like this for each slide, with no other text:
            Slide: [Title of Slide]
            - [Bullet point 1]
            - [Bullet point 2]
            - [Bullet point 3]
            """
            
            res = ollama.chat(model='llama3', messages=[{'role': 'user', 'content': prompt}])
            raw_text = res['message']['content']

            # 2. Initialize the physical PowerPoint file
            # 2. Initialize the physical PowerPoint file using your custom shell
            prs = Presentation("template.pptx")
            
            # Add a Title Slide
            title_slide = prs.slides.add_slide(prs.slide_layouts[0])
            title_slide.shapes.title.text = topic.title()
            title_slide.placeholders[1].text = "Generated by Codebreaker97"

            # 3. Parse Llama's text and build the slides
            slides_data = raw_text.split("Slide:")[1:] # Split into individual slides
            
            for slide_data in slides_data:
                lines = slide_data.strip().split('\n')
                if not lines: continue
                
                slide_title = lines[0].strip()
                bullets = [line.replace('-', '').strip() for line in lines[1:] if line.strip().startswith('-')]
                
                # Create a bullet point slide
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = slide_title
                body_shape = slide.shapes.placeholders[1]
                tf = body_shape.text_frame
                
                for i, bullet in enumerate(bullets):
                    if i == 0:
                        tf.text = bullet
                    else:
                        p = tf.add_paragraph()
                        p.text = bullet

            # 4. Save and Open the file
            filename = f"{topic.replace(' ', '_')}_Presentation.pptx"
            prs.save(filename)
            
            app.safe_append_chat("codebreaker97 (PPT Engine)", f"Presentation complete! Saved locally as {filename}.")
            app.speak_async("Slide deck generation complete.")
            os.startfile(filename) # Pops the PowerPoint open on your screen

        except Exception as e:
            app.safe_append_chat("ERROR", f"PPT Matrix Failure: {e}")

    # Run in background
    threading.Thread(target=ppt_worker, daemon=True).start()
    return True